config/routes.rb
Rails.application.routes.draw do

  resources :items
  devise_for :restaurants, controllers: { sessions: 'restaurants/sessions', registrations: "restaurants/registrations" }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
    
  get 'restaurants/all' => 'restaurants#live_restaurants'
  get 'restaurants/option' => 'restaurants#choosing_option'
  get 'all/restaurants' => 'restaurants#all_restaurants'
  get 'admin/pick_ups' => 'users#admin_pick_ups'
  


  resources :pick_ups
  resources :discounts
  resources :menu_items
  resources :favorite_restaurants
  resources :restaurants do
    member do
      put "like" => "restaurants#vote"
    end
  end
  resources :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@class = "home"
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="landingoptions">
	<button class="landingButtonRestaurant">For Restaurants</button>
	<button class="landingButtonCustomer">For Customers</button>
</div>

<div class="landingoptionsRestaurant">
	<li class="restaurantlanding"><%= link_to "Restaurant Login", new_restaurant_session_path %></li>
	<li class="restaurantlanding"><%= link_to "Restaurant Sign Up", new_restaurant_registration_path %></li>
<!-- 	<li><%= link_to "Restaurant Logout",destroy_restaurant_session_path, method: :delete %></li> -->
</div>

<div class="landingoptionsCustomer">
	<li class="userlanding"><%= link_to "User Login", new_user_session_path %></li>
	<li class="userlanding"><%= link_to "User Sign Up", new_user_registration_path %></li>
<!-- 	<li><%= link_to "User Logout", destroy_user_session_path, method: :delete %></li> -->
</div>

<div class="homeImage">
	<div class="homeText">PLENTY</div>
</div>

<div class="homeDescriptionContain">
	<div class="homeDescription">
		<h1>WHAT IS PLENTY?</h1>
		<p>Our mission is to place the lost value back onto food as something that should be eaten and not thrown away. Through the Our Company app we’re raising awareness of food waste by making surplus food available for collection before a store closes.</p>

		<p>Plenty's goal is to save food, save money and save the planet by placing the lost value back onto food as humankind’s most valuable energy resource, and not something that should just be carelessly throw in the trash. Why? Because if food waste were a country it would be the third largest emitter of greenhouse gases, whilst recovering just half of the food that is lost or wasted could feed the world alone. It’s a problem that doesn’t need to exist – and we’re determined to help solve it.</p>
	</div>
</div>

<div class="homeDiagramContain">
  <h2>HERE'S HOW IT WORKS</h2>
   <div class="HDC">
	<div class="homeDiagram">
		<i class="fa fa-cutlery" aria-hidden="true"></i>
		<p>If a restaurant has an abundance of leftover food close to closing time, they will host a "live discount".</p>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-envelope-o" aria-hidden="true"></i>
		<p>You will recieve notifications for restaurants near you currently hosting a live discount.</p>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-calendar-o" aria-hidden="true"></i>
		<p>If the restaurant closes and still has a food surplus, they will schedule a food pick up.</p>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-truck" aria-hidden="true"></i>
		<p>One of Plenty's drivers will pick up the leftover food and donate it to those in need.</p>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-long-arrow-right" aria-hidden="true"></i>
	</div>
	<div class="homeDiagram">
		<i class="fa fa-globe" aria-hidden="true"></i>
		<p>You and Plenty work together to help feed the hungry, cut down on food waste, and save the planet!</p>
	</div>
  </div>
</div>

<hr></hr>

<div class="homeTotalContain">
	<div class="homeTotal">
		<h3>Plenty's Total Discounts</h3>
		<div class="circleContain">
		<div class="circle"><div class="counter" data-to=<%= Discount.all.count %> data-speed="2500">0</div></div></div>
  	</div>
	<div class="homeTotal2">
		<h3>Plenty's Total Pickups</h3>
		<div class="circleContain">
		<div class="circle"><div class="counter" data-to=<%= PickUp.all.count %> data-speed="2500">0</div></div></div>
  	</div>
</div>

<hr></hr>

<div class="foodWasteGallery">
	<div class="foodWasteContain">
	<div class="foodWasteImage">
	</div>
	<div class="foodWasteFact1">
		1.3 billion tons of food are wasted every year.
	</div></div>
	<div class="foodWasteContain">
	<div class="foodWasteImage2">
	</div>
	<div class="foodWasteFact">
		One quarter of all wasted food could feed the 795 million undernourished people around the world who suffer from hunger.
	</div></div>
	<div class="foodWasteContain">
	<div class="foodWasteImage3">
	</div>
	<div class="foodWasteFact">
		If wasted food was a country, it would be the third largest producer of carbon dioxide in the world, after the United States and China.
	</div></div>
	<div class="foodWasteContain">
	<div class="foodWasteImage4">
	</div>
	<div class="foodWasteFact">
		Food waste generates 3.3 billions tons of carbon dioxide, which accelerates global climate change.
	</div></div>
</div>

<footer class="homeFooter">
	© 2017 PLENTY.com
</footer>

<script>
var stats_counter = function() {
  if($('.counter').length > 0) { 
    function increment($this, speed){
      var current = parseInt($this.html(), 10);
      $this.html(++current);
      if(current !== $this.data('to')){
        setTimeout(function(){increment($this, speed)}, speed);
      }
    }  
    $('.counter').each(function(index) {
      increment($(this), parseInt($(this).data('speed')));
    });
  }
}
stats_counter();


document.querySelector(".landingButtonRestaurant").addEventListener("click", function() {
	document.querySelector(".landingoptionsRestaurant").style.display = "block";
	document.querySelector(".landingoptionsCustomer").style.display = "none";
})

document.querySelector(".landingButtonCustomer").addEventListener("click", function() {
	document.querySelector(".landingoptionsRestaurant").style.display = "none";
	document.querySelector(".landingoptionsCustomer").style.display = "block";
})

</script>