config/routes.rb
Rails.application.routes.draw do

  resources :items
  devise_for :restaurants, controllers: { sessions: 'restaurants/sessions', registrations: "restaurants/registrations" }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
    
  get 'restaurants/all' => 'restaurants#live_restaurants'
  get 'restaurants/option' => 'restaurants#choosing_option'
  get 'all/restaurants' => 'restaurants#all_restaurants'
  get 'admin/pick_ups' => 'users#admin_pick_ups'
  


  resources :pick_ups
  resources :discounts
  resources :menu_items
  resources :favorite_restaurants
  resources :restaurants do
    member do
      put "like" => "restaurants#vote"
    end
  end
  resources :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_votable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :menu_items, :dependent => :destroy
	has_many :pick_ups, :dependent => :destroy
	has_many :discounts, :dependent => :destroy
	has_many :favorite_restaurants, :dependent => :destroy
	has_many :users, through: :favorite_restaurants, :dependent => :destroy
	mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode
end

app/controllers/restaurants/confirmations_controller.rb
class Restaurants::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/restaurants/omniauth_callbacks_controller.rb
class Restaurants::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/restaurants/passwords_controller.rb
class Restaurants::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/restaurants/registrations_controller.rb
class Restaurants::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end
  
  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_menu_item_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurants/sessions_controller.rb
class Restaurants::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    restaurant_path(resource)
  end
end

app/controllers/restaurants/unlocks_controller.rb
class Restaurants::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :vote]
  respond_to :js, :json, :html
  before_action :authenticate_restaurant!, except: [:live_restaurants, :all_restaurants, :show]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurant = current_restaurant
    @class = "restaurant"
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = current_restaurant if restaurant_signed_in?
  end

  # GET /restaurants/new
  def new
    @class = "restaurantNew"
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def vote
    if current_user
      if !current_user.liked? @restaurant
        FavoriteRestaurant.create ([
          {user_id: current_user.id, restaurant_id: @restaurant.id}
        ])
        @restaurant.liked_by current_user
      elsif current_user.liked? @restaurant
        @rest = FavoriteRestaurant.where(:user_id => current_user.id, :restaurant_id => @restaurant.id)
        p @rest
        @rest.delete_all
        @restaurant.unliked_by current_user
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def live_restaurants
    @restaurants = Restaurant.all
    @discounts = Discount.live
  end
  def all_restaurants
    @restaurants = Restaurant.all
  end

  def choosing_option
    @pick_ups = PickUp.all
    @discounts = Discount.all
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:cname, :address, :number, :photo, :menu, :longitude, :langitude)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cname %>
    <%= form.text_field :cname, id: :restaurant_cname %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :restaurant_number %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :restaurant_photo %>
  </div>

  <div class="field">
    <%= form.label :menu %>
    <%= form.text_field :menu, id: :restaurant_menu %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.number_field :longitude, id: :restaurant_longitude %>
  </div>

  <div class="field">
    <%= form.label :langitude %>
    <%= form.number_field :langitude, id: :restaurant_langitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/all_restaurants.html.erb
<div class="allPagesHeader"><div class="plentyHeader"><i class="fa fa-globe" aria-hidden="true"></i>PLENTY</div>
    <span class="allPagesHeaderText"><em>save food, save money and save the planet.</em></span>
  </div>

<h2 class="all-restaurant-page-title">PLENTY is happy to have so many partnerships!</h2>
<h6 class="all-restaurant-page-subtitle">Listed below are all the restaurants associated with PLENTY. Each restaurant has either helped customers save money, fed those in need, and/or contributed to saving our planet by minimizing food wastage.</h6>

<p class="mobile-rules">Pinch or double tap to zoom</p>
<p class="mobile-rules">Hold and slide to move around map</p>
<p class="mobile-rules">Tap on icon for more information</p>

<div class="live-restaurants-container">

  <div id="map"></div>

  <div class="live-discount-restaurants-col">
    <h1 class="restaurants-list-heading">All Restaurants</h1>
    <% @restaurants.each do |restaurant| %>
      <div class="live-discount-restaurants-list">
        <h3 class="restaurant-name-in-list"><%= link_to restaurant.cname, restaurant %></h3>
        <h5 class="restaurant-address-in-list"><%= restaurant.address %></h5>
      </div>
    <% end %>
  </div>

</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDzDUyA7JETU9aaofrnQdoTqXCLEBrSywA&libraries=places" type="text/javascript">
</script>
<script type="text/javascript">

var infoWindow, map;
function initMap() {
	map = new google.maps.Map(document.getElementById('map'), {
	  center: {lat: 40.714623, lng: -74.006605},
	  zoom: 14,
	  styles: [
	  	{
	  		featureType: "poi",
	  		elementType: "labels",
	 		stylers: [
	  			{visibility: "off"}
	  		]
		}
	]
	});
  var infoWindow = new google.maps.InfoWindow

  var restaurants = [
    <% @restaurants.each do |restaurant| %>
      {
        coords:{lat:<%= restaurant.latitude %>,lng:<%= restaurant.longitude %>},
        content: "<h3><%= restaurant.cname %></h3> <h6><%= restaurant.address %></h6>"
      },
    <% end %>
  ]
  
  for(var i = 0; i < restaurants.length; i++){
    addMarker(restaurants[i]);
  }
  function addMarker(props){
    var marker = new google.maps.Marker({
    position: props.coords,
    map: map

    });
    var infoWindow = new google.maps.InfoWindow({
      content: props.content 
    });
    marker.addListener('click', function(){
      infoWindow.open(map, marker);
    });  
  }
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var pos = {
            lat: position.coords.latitude,
            lng: position.coords.longitude
          };
          infoWindow.setPosition(pos);
          infoWindow.setContent('Current Location');
          infoWindow.open(map);
          map.setCenter(pos);
        }, function() {
          handleLocationError(true, infoWindow, map.getCenter());
        });
      } else {
        // Browser doesn't support Geolocation
        handleLocationError(false, infoWindow, map.getCenter());
      }
};

$(function () {
        initialize();
    });

var placeSearch, autocomplete;
var componentForm = {
	street_number: 'short_name',
	route: 'long_name',
	locality: 'long_name',
	administrative_area_level_1: 'short_name',
	country: 'long_name',
	postal_code: 'short_name'
};

function initialize() {
    autocomplete = new google.maps.places.Autocomplete(
        (document.getElementById('autocomplete')),
        {types: ['geocode']});
    autocomplete.addListener('place_changed', fillInAddress);
    console.log(autocomplete);
    console.log();
}

function fillInAddress() {
    var place = autocomplete.getPlace();

    for (var component in componentForm) {
      document.getElementById(component).value = '';
      document.getElementById(component).disabled = false;
    }

    for (var i = 0; i < place.address_components.length; i++) {
      var addressType = place.address_components[i].types[0];
      if (componentForm[addressType]) {
        var val = place.address_components[i][componentForm[addressType]];
        document.getElementById(addressType).value = val;
      }
    }
  }



      function handleLocationError(browserHasGeolocation, infoWindow, pos) {
        infoWindow.setPosition(pos);
        infoWindow.setContent(browserHasGeolocation ?
                              'Error: The Geolocation service failed.' :
                              'Error: Your browser doesn\'t support geolocation.');
        infoWindow.open(map);
      }

setTimeout(initMap, 10);
</script>

app/views/restaurants/choosing_option.html.erb
<div class="allPagesHeader"><div class="plentyHeader"><i class="fa fa-globe" aria-hidden="true"></i>PLENTY</div>
		<span class="allPagesHeaderText"><em>save food, save money and save the planet.</em></span>
	</div>

<% if current_restaurant %>
	<div class="choose_option_forms container">
	<h1 class="choosing-option-title">Closing soon?<br> Have extra food? <br> Just choose an option below, we'll take care of the rest.</h1>

		<div class="col-md-6" id="border-option">
			
			<h3 class="choosing-option-subtitle-1">Lower your prices here and watch that food go.</h3>

			      <div class="modal-body-discount-form">
						<%= render partial: 'discounts/form', locals: {discount: Discount.new}, remote: true %>
			      </div>
		</div>
		<div class="col-md-6">
			<h3 class="choosing-option-subtitle-2">Help Contribute in feeding those in need. Request a pick up and we'll swing by.</h3>
				
			<%= link_to pick_ups_path(:json), method: :post, remote: true do %> 
		      <div class="button-request-pick-up">
		      		<input value="Request a Pick-up" type="submit" />
		      </div>
		     <% end %>
		 </div>

	</div>
<% end %>

<script type="text/javascript">
	var request, message;
	request = document.querySelector('.button-request-pick-up');
	message = document.querySelector('.choosing-option-subtitle-2');
	request.addEventListener('click', function(){
		request.style.display = 'none';
		message.innerText = "Thank You for your donation! One of our Plenty employees will be there shortly to pick up your donation. A confirmation email has been sent to you as well."
	})
</script>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Cname</th>
      <th>Address</th>
      <th>Number</th>
      <th>Photo</th>
      <th>Menu</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
      <tr>
        <td><%= @restaurant.cname %></td>
        <td><%= @restaurant.address %></td>
        <td><%= @restaurant.number %></td>
        <td></td>
        <td><%= link_to 'Show Menu(s)', menu_items_path %></td>
        <td><%= link_to 'Show', @restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></td>
        <td><%= link_to 'Destroy', @restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/restaurants.js.erb
<% if current_user %>
	$("h1").css("color", "red");
<% end %>

app/views/restaurants/show.html.erb
<div class="allPagesHeader"><div class="plentyHeader"><i class="fa fa-globe" aria-hidden="true"></i>PLENTY</div>
    <span class="allPagesHeaderText"><em>save food, save money and save the planet.</em></span>
  </div>

<div class="restaurantHome">

<h1>
  <%= @restaurant.cname %>
</h1>

<p class="restaurantInfo">
  <span class="fa fa-map-marker" aria-hidden="true"></span> <%= @restaurant.address %>
</p>

<p class="restaurantInfo">
  <span class="fa fa-phone" aria-hidden="true"></span> <%= @restaurant.number %>
</p>

<p class="restaurantInfo">
  <%= link_to like_restaurant_path(@restaurant), class:"fav-btn", method: :put, remote: :true do %>
  <i class='fa fa-star'></i><% end %>
  <em><span class="favStatus"></span></em>
</p>

<p><%= image_tag(@restaurant.image) if @restaurant.image? %></p>

</div><!--  end of restaurantHome -->

<div class="restaurantHomeMenu">
<h2><%= @restaurant.cname %> Menu</h2>
<div class="restaurantShowNav"><% if current_restaurant %>
  <% if current_restaurant.id == @restaurant.id %>
    <p><%= link_to 'Add Menu Item(s)', edit_menu_item_path(@restaurant.menu_items.ids) %></p>
    <p><%= link_to 'Delete My Account', @restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></p>
  <% end %>
<% end %>

<button class="apps">Appetizers</button>
<button class="maindishes">Main Dishes</button>
<button class="drinks">Drinks</button>
<button class="desserts">Desserts</button>

<div class="restaurantHomeMenuItems">
<div class="menuItemAppetizers">
<h3>Appetizers</h3>
<% @restaurant.menu_items.each do |menu| %>
  <% menu.items.appetizers.each do |item| %>
    <p><strong><%= item.item %></strong> $<%= item.price %></p>
    <p><%= item.description %></p>
    <p>Price During Discount Time: $<%= item.starting_range %>-<%= item.ending_range %></p>
    <% if current_restaurant %>
    <% if current_restaurant.id == @restaurant.id %>
      <p><%= link_to 'Delete Item', item, method: :delete, data: { confirm: 'Are you sure?' } %></p>
        <p><%= link_to 'Edit Item', edit_item_path(item) %></p>
    <% end %>
    <% end %>
  <% end %>
<% end %>
</div>

<div class="menuItemMainDishes">
<h3>Main Dishes</h3>
<% @restaurant.menu_items.each do |menu| %>
  <% menu.items.maindishes.each do |item| %>
    <p><strong><%= item.item %></strong> $<%= item.price %></p>
    <p><%= item.description %></p>
    <p>Price During Discount Time: $<%= item.starting_range %>-<%= item.ending_range %></p>
    <% if current_restaurant %>
    <% if current_restaurant.id == @restaurant.id %>
      <p><%= link_to 'Delete Item', item, method: :delete, data: { confirm: 'Are you sure?' } %><p>
      <p><%= link_to 'Edit Item', edit_item_path(item) %></p>
    <% end %>
    <% end %>
  <% end %>
<% end %>
</div>

<div class="menuItemDesserts">
<h3>Desserts</h3>
<% @restaurant.menu_items.each do |menu| %>
  <% menu.items.desserts.each do |item| %>
    <p><strong><%= item.item %></strong> $<%= item.price %></p>
    <p><%= item.description %></p>
    <p>Price During Discount Time: $<%= item.starting_range %>-<%= item.ending_range %></p>
    <% if current_restaurant %>
    <% if current_restaurant.id == @restaurant.id %>
      <p><%= link_to 'Delete Item', item, method: :delete, data: { confirm: 'Are you sure?' } %><p>
      <p><%= link_to 'Edit Item', edit_item_path(item) %></p>
    <% end %>
    <% end %>
  <% end %>
<% end %>
</div>

<div class="menuItemDrinks">
<h3>Drinks</h3>
<% @restaurant.menu_items.each do |menu| %>
  <% menu.items.drinks.each do |item| %>
    <p><strong><%= item.item %></strong> $<%= item.price %></p>
    <p><%= item.description %></p>
    <p>Price During Discount Time: $<%= item.starting_range %>-<%= item.ending_range %></p>
    <% if current_restaurant %>
    <% if current_restaurant.id == @restaurant.id %>
      <p><%= link_to 'Delete Item', item, method: :delete, data: { confirm: 'Are you sure?' } %><p>
      <p><%= link_to 'Edit Item', edit_item_path(item) %></p>
    <% end %>
    <% end %>
  <% end %>
<% end %>
</div>
</div> <!-- end of restaurantHomeMenuItems -->
</div> <!-- end of restaurantHomeMenu -->

<script>

document.querySelector(".apps").addEventListener("click", function () {
  document.querySelector(".menuItemAppetizers").style.opacity = "1";
  document.querySelector(".menuItemMainDishes").style.opacity = "0";
  document.querySelector(".menuItemDrinks").style.opacity = "0";
  document.querySelector(".menuItemDesserts").style.opacity = "0";
})

document.querySelector(".maindishes").addEventListener("click", function () {
  document.querySelector(".menuItemMainDishes").style.opacity = "1";
  document.querySelector(".menuItemAppetizers").style.opacity = "0";
  document.querySelector(".menuItemDrinks").style.opacity = "0";
  document.querySelector(".menuItemDesserts").style.opacity = "0";
})

document.querySelector(".drinks").addEventListener("click", function () {
  document.querySelector(".menuItemDrinks").style.opacity = "1";
  document.querySelector(".menuItemMainDishes").style.opacity = "0";
  document.querySelector(".menuItemDesserts").style.opacity = "0";
  document.querySelector(".menuItemAppetizers").style.opacity = "0";
})

document.querySelector(".desserts").addEventListener("click", function () {
  document.querySelector(".menuItemDesserts").style.opacity = "1";
  document.querySelector(".menuItemAppetizers").style.opacity = "0";
  document.querySelector(".menuItemMainDishes").style.opacity = "0";
  document.querySelector(".menuItemDrinks").style.opacity = "0";
})

<% if !current_user %>
  $('.fav-btn').css("color", "black");
  $('.favStatus').html("Add to favorites");
<% end %>

<% if current_user %>
<% if FavoriteRestaurant.where(:user_id => current_user.id, :restaurant_id => @restaurant.id).exists? %>
  $('.fav-btn').css("color", "#ffd700");
  $('.favStatus').html("Remove from favorites");
<% end %>
<% end %>

<% if current_user %>
<% if !FavoriteRestaurant.where(:user_id => current_user.id, :restaurant_id => @restaurant.id).exists? %>
  $('.fav-btn').css("color", "black");
  $('.favStatus').html("Add to favorites");
<% end %>
<% end %>


</script>

app/views/restaurants/vote.js.erb
<% if !current_user %>
	$('#notice').html("You must be signed in to add a restaurant to your favorites list. <a href='/users/sign_in'>Click Here to Sign In</a>");
<% end %>
<% if current_user %>
<% if current_user.liked? @restaurant %>
	$('.fav-btn').addClass('liked');
	$('#notice').html("Added to Favorites.");
	$('.fav-btn').css("color", "#ffd700");
	$('.favStatus').html("Remove from favorites");
<% else %>
	$('.fav-btn').removeClass('liked');
	$('#notice').html("Removed from Favorites.");
	$('.fav-btn').css("color", "black");
	$('.favStatus').html("Add to favorites");
<% end %>
<% end %>