config/routes.rb
Rails.application.routes.draw do

  resources :items
  devise_for :restaurants, controllers: { sessions: 'restaurants/sessions', registrations: "restaurants/registrations" }
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: "users/registrations" }
    
  get 'restaurants/all' => 'restaurants#live_restaurants'
  get 'restaurants/option' => 'restaurants#choosing_option'
  get 'all/restaurants' => 'restaurants#all_restaurants'
  get 'admin/pick_ups' => 'users#admin_pick_ups'
  


  resources :pick_ups
  resources :discounts
  resources :menu_items
  resources :favorite_restaurants
  resources :restaurants do
    member do
      put "like" => "restaurants#vote"
    end
  end
  resources :users

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/favorite_restaurant.rb
class FavoriteRestaurant < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/favorite_restaurants_controller.rb
class FavoriteRestaurantsController < ApplicationController
  before_action :set_favorite_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /favorite_restaurants
  # GET /favorite_restaurants.json
  def index
    @favorite_restaurants = FavoriteRestaurant.all
  end

  # GET /favorite_restaurants/1
  # GET /favorite_restaurants/1.json
  def show
  end

  # GET /favorite_restaurants/new
  def new
    @favorite_restaurant = FavoriteRestaurant.new
  end

  # GET /favorite_restaurants/1/edit
  def edit
  end

  # POST /favorite_restaurants
  # POST /favorite_restaurants.json
  def create
    @favorite_restaurant = FavoriteRestaurant.new(favorite_restaurant_params)

    respond_to do |format|
      if @favorite_restaurant.save
        format.html { redirect_to @favorite_restaurant, notice: 'Favorite restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @favorite_restaurant }
      else
        format.html { render :new }
        format.json { render json: @favorite_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorite_restaurants/1
  # PATCH/PUT /favorite_restaurants/1.json
  def update
    respond_to do |format|
      if @favorite_restaurant.update(favorite_restaurant_params)
        format.html { redirect_to @favorite_restaurant, notice: 'Favorite restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @favorite_restaurant }
      else
        format.html { render :edit }
        format.json { render json: @favorite_restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorite_restaurants/1
  # DELETE /favorite_restaurants/1.json
  def destroy
    @favorite_restaurant.destroy
    respond_to do |format|
      format.html { redirect_to favorite_restaurants_url, notice: 'Favorite restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite_restaurant
      @favorite_restaurant = FavoriteRestaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_restaurant_params
      params.require(:favorite_restaurant).permit(:user_id, :restaurant_id)
    end
end

app/helpers/favorite_restaurants_helper.rb
module FavoriteRestaurantsHelper
end

app/views/favorite_restaurants/_form.html.erb
<div id="favrestaurant">
<%= form_with(model: favorite_restaurant, local: true) do |form| %>
  <% if favorite_restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favorite_restaurant.errors.count, "error") %> prohibited this favorite_restaurant from being saved:</h2>

      <ul>
      <% favorite_restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">

    <%= form.text_field :user_id, id: :favorite_restaurant_user_id, placeholder: "User" %>
  </div>

  <div class="field">

    <%= form.text_field :restaurant_id, id: :favorite_restaurant_restaurant_id, placeholder: "Restaurant" %>
  </div>

  <div class="actions">
    <center><%= form.submit "Submit", class: 'favrbutton' %></center>
  </div>
<% end %>
</div>

app/views/favorite_restaurants/edit.html.erb
<h1>Editing Favorite Restaurant</h1>

<%= render 'form', favorite_restaurant: @favorite_restaurant %>

<%= link_to 'Show', @favorite_restaurant %> |
<%= link_to 'Back', favorite_restaurants_path %>

app/views/favorite_restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Favorite Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_restaurants.each do |favorite_restaurant| %>
      <tr>
        <td><%= favorite_restaurant.user %></td>
        <td><%= favorite_restaurant.restaurant %></td>
        <td><%= link_to 'Show', favorite_restaurant %></td>
        <td><%= link_to 'Edit', edit_favorite_restaurant_path(favorite_restaurant) %></td>
        <td><%= link_to 'Destroy', favorite_restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Favorite Restaurant', new_favorite_restaurant_path %>

app/views/favorite_restaurants/new.html.erb
<div id="favrestaurant"><center><h1>New Favorite Restaurant</h1></center></div>

<%= render 'form', favorite_restaurant: @favorite_restaurant %>

<%= link_to 'Back', favorite_restaurants_path %>

app/views/favorite_restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite_restaurant.user.fname %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @favorite_restaurant.restaurant.cname %>
</p>

<%= link_to 'Edit', edit_favorite_restaurant_path(@favorite_restaurant) %> |
<%= link_to 'Back', favorite_restaurants_path %>